### ISSUE TITLE
Uses a non-SPDX-compliant identifier for its license

### ISSUE THREAD

**Issue by jjnicola** [BurntSushi/winapi-util#15]
Hello, I am having an issue when I perform a license check. It seems that the identifier `Unlicense/MIT` is non-SPDX-complieant and the correct one should be `Unlicense OR MIT`.
Thanks a lot.

**Comment by BurntSushi** [comment]
Closed by https://github.com/BurntSushi/winapi-util/commit/8b0872075d26d1b67f461306d7f58fb4e1e694f4
