### ISSUE TITLE
Bash on Windows / Cygwin detection

### ISSUE THREAD

**Issue by 3tilley** [BurntSushi/winapi-util#17]
Hello,

I've read #6 so I have an idea of your thoughts, but I wanted to check how you feel about adding msys / cygwin detection routines. As you're no doubt aware they have some different considerations when it comes to handling terminal behaviour. In my case I'm trying to fix a bug relating to `if shell.is_bash() { linux_behaviour() }` that fails on Windows.

I haven't seen a Rust implementation of the common routine that exists in other languages, [zig](https://github.com/ziglang/zig/blob/1c85b0acbb5148dec7ff671e767354f3df5c6b83/lib/std/os.zig#L3286) [go](https://github.com/restic/restic/blob/45962c28475e12fe50bc539c48cdcd5209264fbb/internal/ui/termstatus/terminal_windows.go#L120), [c](https://github.com/msys2/MINGW-packages/blob/808c765989cb400a44485d8fbebf94264532ac9b/mingw-w64-lua53/cygpty.patch#L181) - there are various quality of Python examples too.

One the one hand, this seems like the obvious place for the logic to live, if it doesn't go into a crate called `is-msys-or-cygwin`. It's similar in nature to the other items here in terms of code, and purpose. I also think this can be done without further dependencies.

On the other hand, I'm pretty sure it'll be an FFI call and therefore unsafe.

Do you have any thoughts? Have you handled this issue differently elsewhere?

**Comment by BurntSushi** [comment]
This request looked a bit confused. On the one hand, you seem to be asking to detect msys/cygwin but on the other, your `shell.is_bash()` snippet suggests what you want is _shell_ detection. AIUI, msys/cygwin are not shells. They are terminal emulators.

Can you elaborate a bit more on the motivation here?

I note that I was the one who originally brought code very similar to what you've linked [to the `atty` crate](https://github.com/softprops/atty/blob/6633c0e1446aa19e6cd00e00e39770da43081bda/src/lib.rs#L116-L154). So I'm not sure it's true that there isn't a Rust implementation. Indeed the logic got moved to the standard library via the [`IsTerminal`](https://doc.rust-lang.org/std/io/trait.IsTerminal.html) trait.

But that only queries for "is a terminal or not." You seem to be after something different. It's not clear to me.

**Comment by 3tilley** [comment]
Thanks for that snippet, I was surprised that I couldn't find it on GH but I was searching for the regex, rather than a check without an regex dependency. To be honest I did check your repos looking for it as I'd assumed you'd have to have tackled this for at least ripgrep. I'm a big fan of your work!

As for the purpose, you're correct to say this is a little confused. I was hoping to use the general function in a couple of different usecases. For example if you want to print a path, you could say `if !windows() || is_msys() {print_forward_slashes()}`. Whether that's a good idea I guess is a separate discussion though. If you know of any semi-official resources for writing cross-platform CLIs I'd be really interested.

In the original case, I think I'm safe to say `if shell.is_bash() && is_windows()` and be confident that I'm on msys/cygwin as I'm not aware of any other widely-used bash-on-Windows implementations

Anyway thanks for your swift reply, I'll close this issue.
